### ISSUE TITLE
Some works that have not been included

### ISSUE THREAD

**Issue by haowang-cqu** [ThuCCSLab/lm-ssp#4]
👍 Thank you for creating and maintaining such a great repository. I found that these works have not been included and hope they can be added.

|Title | Link | Code | Venue | Classification | Model | Comment|
|-- | -- | -- | -- | -- | -- | --|
|Query-Relevant Images Jailbreak Large Multi-Modal Models| https://arxiv.org/abs/2311.17600| https://github.com/isXinLiu/MM-SafetyBench| arXiv'23 | A1. Jailbreak | VLM| |
|GUARD: Role-playing to Generate Natural-language Jailbreakings to Test Guideline Adherence of Large Language Models| https://arxiv.org/abs/2402.03299| | arXiv'24 | A1. Jailbreak | LLM| |
|On the Robustness of Large Multimodal Models Against Image Adversarial Attacks| https://arxiv.org/abs/2312.03777| | arXiv'23 | B1. Adversarial Examples | VLM| |
|VL-Trojan: Multimodal Instruction Backdoor Attacks against Autoregressive Visual Language Models| https://arxiv.org/abs/2402.13851| | arXiv'24 | B2. Poisoning | VLM| |

**Comment by ThuCCSLab** [comment]
Thanks for your recommendation.
These papers have been added to the list. 
Many thanks! 👍

**Comment by leonardtang** [comment]
This might also be interesting as a leaderboard: https://huggingface.co/blog/leaderboards-on-the-hub-haizelab
