### ISSUE TITLE
Some of my related works

### ISSUE THREAD

**Issue by xavihart** [ThuCCSLab/lm-ssp#5]
| Title | Link  | Code |   Venue |  Classification |  Model | Comment | 
| ---- |---- |---- |---- |---- |----|----| 
|  Towards More Effective Protection Against Diffusion-Based Mimicry with Score Distillation | https://arxiv.org/abs/2311.12832  | https://github.com/xavihart/Diff-Protect    |  ICLR 2024 | C2. Copyright | Diffusion Model  | protective perturbation of diffusion model | 
|  Diffusion-Based Adversarial Sample Generation for Improved Stealthiness and Controllability | https://arxiv.org/abs/2305.16494  | https://github.com/xavihart/Diff-PGD    |  NeurIPS 2023 | B1. Adversarial Samples | Diffusion Model  | generate stealthy adversarial samples |

**Comment by ThuCCSLab** [comment]
Great works! We will add them in out next update. Thanks!
